<?php

namespace Wac\TechWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListRepository extends EntityRepository
{
}
